using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// “G‚Ì’e‚Ìƒ_ƒ[ƒW‚ğ’²®‚·‚éˆ—
public class enemy_bullet_damage : MonoBehaviour
{
    // ƒ_ƒ[ƒW—Ê
    public int damage = 10;
    // ’e‚ªËo‚³‚ê‚Ä‚©‚çÁ‚¦‚é‚Ü‚Å‚ÌŠÔ
    public float destroy_time = 5f;
    void Update()
    {
        Destroy(this.gameObject, destroy_time);
    }
    // “G‚Ì’e‚Æ‚ÌÚGˆ—
    private void OnTriggerEnter2D(Collider2D other)
    {
        // player‚É’e‚ªÚG‚µ‚½ê‡‚Ìˆ—
        if (other.gameObject.CompareTag("Player"))
        {

            var damagetarget = other.gameObject.GetComponent<IDamagable>();


            if (damagetarget != null)
            {
                other.gameObject.GetComponent<IDamagable>().AddDamage(damage);
                other.gameObject.GetComponent<IDamagable>().AddEnergy(damage);
                other.gameObject.GetComponent<IDamagable>().AddScore(damage);
            }
            Destroy(this.gameObject);
        }
    }
}
